include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
    avoid_print: true
    require_trailing_commas: false
    sort_child_properties_last: true
    use_key_in_widget_constructors: true
    sized_box_for_whitespace: false
    prefer_single_quotes: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    dangling_library_doc_comments: ignore
    deprecated_member_use: ignore
    library_private_types_in_public_api: ignore
    unnecessary_brace_in_string_interps: ignore
    unnecessary_nullable_for_final_variable_declarations: ignore
